"""TRACTOR test vectors → component-spec §2.3 test packages.

The generated package is::

    <out>/
    ├── run_test.sh          # sh shim: python3 run_vectors.py <test_data> <artifact>
    ├── run_vectors.py       # verbatim copy of proctor/testing/vector_runner.py
    └── test_data/vectors/   # the case's vectors, copied as-is

Fidelity rule: the corpus harness is the oracle — the runner mirrors
``tools/cando2`` comparison semantics (see its docstring). The
comparator is Python rather than pure POSIX sh because exact-bytes and
regex matching are not honestly expressible in shell; ``python3`` is
already required by every stage adapter.

Library cases (``lib_state_in``/``lib_state_out`` vectors) bundle the
case's cando harness crate into ``test_data/runner`` with its cando2
path dependency rewritten to the corpus checkout (plan T3); at run
time the harness is built once (cached) and drives the ``.so``.
"""

from __future__ import annotations

import json
import shutil
from dataclasses import dataclass
from pathlib import Path

_RUNNER_SOURCE = Path(__file__).parent / "vector_runner.py"

RUN_TEST_SH = """#!/bin/sh
# Generated by `proctor make-tests` (component spec §2.3).
#   $1 = test_data directory, $2 = compiled artifact
set -eu
exec python3 "$(dirname "$0")/run_vectors.py" "$1" "$2"
"""


class VectorError(ValueError):
    """The vectors cannot be converted into a runnable test package."""


@dataclass(frozen=True)
class GeneratedPackage:
    package_dir: Path
    vectors: int
    unsupported: tuple[str, ...]  # names skipped at run time (setup/file-changes)
    library: bool = False  # bundles the case's cando harness crate


def find_vectors_dir(source: Path) -> Path:
    """Accepts a case directory (containing ``test_vectors/``) or a
    vectors directory itself."""
    if (source / "test_vectors").is_dir():
        return source / "test_vectors"
    if source.is_dir() and (
        any(source.glob("*.json")) or any(p.is_dir() for p in source.iterdir())
    ):
        return source
    raise VectorError(f"no test vectors found at {source} (or its test_vectors/)")


def _vector_entries(vectors_dir: Path) -> list[Path]:
    entries = sorted(
        (p for p in vectors_dir.iterdir() if p.is_dir() or p.suffix == ".json"),
        key=lambda p: p.name,
    )
    if not entries:
        raise VectorError(f"{vectors_dir} contains no vectors")
    return entries


def _scan_entry(entry: Path) -> tuple[bool, str | None]:
    """(is_library_vector, runtime-unsupported-reason)."""
    vector_file = entry / "cando_vector.json" if entry.is_dir() else entry
    try:
        data = json.loads(vector_file.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise VectorError(f"unreadable vector {vector_file}: {exc}") from exc
    if not isinstance(data, dict):
        raise VectorError(f"{vector_file} is not a JSON object")
    is_library = (
        data.get("lib_state_in") is not None or data.get("lib_state_out") is not None
    )
    unsupported = None
    if entry.is_dir() and (
        (entry / "setup").exists() or (entry / "file_changes.tar.gz").exists()
    ):
        unsupported = "setup/file-changes"
    return is_library, unsupported


def _bundle_harness_crate(case_runner: Path, dest: Path) -> None:
    """Copy the case's cando harness crate into the package, rewriting
    its relative ``cando2`` path dependency to an absolute one (the
    corpus checkout). Library packages are therefore machine-local —
    they are generated per run, not committed."""
    import tomllib

    shutil.copytree(
        case_runner,
        dest,
        ignore=shutil.ignore_patterns("target", "fuzz", "Cargo.lock"),
    )
    cargo_file = dest / "Cargo.toml"
    cargo = tomllib.loads(cargo_file.read_text(encoding="utf-8"))
    dep = cargo.get("dependencies", {}).get("cando2")
    if not isinstance(dep, dict) or "path" not in dep:
        raise VectorError(f"{case_runner}/Cargo.toml has no cando2 path dependency")
    relative = str(dep["path"])
    absolute = (case_runner / relative).resolve()
    if not (absolute / "Cargo.toml").is_file():
        raise VectorError(
            f"cando2 crate not found at {absolute} "
            f"(is the Test-Corpus submodule initialized?)"
        )
    text = cargo_file.read_text(encoding="utf-8")
    if relative not in text:
        raise VectorError(f"cannot rewrite cando2 path in {cargo_file}")
    cargo_file.write_text(text.replace(relative, str(absolute), 1), encoding="utf-8")


def generate_test_package(source: Path, out_dir: Path) -> GeneratedPackage:
    """Generate a §2.3 test package from a case's TRACTOR vectors.

    Executable cases produce a self-contained package. Library cases
    (``lib_state_*`` vectors) additionally bundle the case's cando
    harness crate (``<case>/runner``); at run time the harness is built
    once (cached) and drives the ``.so`` per vector — so library
    packages need ``cargo`` on the test machine.
    """
    vectors_dir = find_vectors_dir(source)
    entries = _vector_entries(vectors_dir)

    library_vectors = []
    unsupported = []
    for entry in entries:
        is_library, reason = _scan_entry(entry)
        if is_library:
            library_vectors.append(entry.name)
        if reason:
            unsupported.append(entry.name)

    case_runner = vectors_dir.parent / "runner"
    if library_vectors and not (case_runner / "Cargo.toml").is_file():
        raise VectorError(
            f"library-state vectors need the case's cando harness crate, "
            f"but {case_runner} has none: {library_vectors}"
        )

    if out_dir.exists() and any(out_dir.iterdir()):
        raise VectorError(f"output package directory {out_dir} is not empty")
    dest_vectors = out_dir / "test_data" / "vectors"
    dest_vectors.mkdir(parents=True, exist_ok=True)
    for entry in entries:
        if entry.is_dir():
            shutil.copytree(entry, dest_vectors / entry.name)
        else:
            shutil.copy2(entry, dest_vectors / entry.name)

    if library_vectors:
        _bundle_harness_crate(case_runner, out_dir / "test_data" / "runner")

    shutil.copy2(_RUNNER_SOURCE, out_dir / "run_vectors.py")
    script = out_dir / "run_test.sh"
    script.write_text(RUN_TEST_SH, encoding="utf-8")
    script.chmod(0o755)

    return GeneratedPackage(
        package_dir=out_dir,
        vectors=len(entries),
        unsupported=tuple(unsupported),
        library=bool(library_vectors),
    )
