#!/usr/bin/env python3
"""Example stage built ON the framework's shared components.

Demonstrates the intended wiring for LLM stages that don't bring their
own agent machinery:

- ``StageInput``/``StageOutput`` from ``proctor.contracts`` instead of
  hand-rolled JSON;
- ``LlmClient`` configured straight from the envelope's
  ``framework.llm`` settings (provider, model, retries, rate limits,
  and provider-specific ``extra`` such as reasoning effort — all come
  from the pipeline config, not this code);
- ``UsageTracker`` writing per-call records to the envelope's
  ``usage_log`` so ``proctor report`` sees this stage's cost;
- a stage-local ``PromptLibrary`` with a versioned template.

The task itself is deliberately harmless: copy the project through and
add an LLM-written ``TRANSLATION_NOTES.md``. Real stages replace that
with transformations + a build/test validation loop.
"""

from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path

from proctor.contracts import (
    ModelInfo,
    OutputDestinations,
    PromptUse,
    StageInput,
    StageOutput,
    UsageSummary,
)
from proctor.llm.client import LlmClient
from proctor.llm.types import LlmError, Message, Request, RequestMetadata
from proctor.prompts.library import PromptLibrary
from proctor.usage.tracker import UsageTracker

STAGE_ID = "example_llm"
STAGE_VERSION = "0.1.0"


def pick_source_file(project: Path, config: dict) -> Path:
    configured = config.get("source_file", "")
    candidates = (
        [project / configured]
        if configured
        else [
            project / "lib.rs",
            project / "src" / "lib.rs",
            project / "src" / "main.rs",
        ]
    )
    for candidate in candidates:
        if candidate.is_file():
            return candidate
    raise FileNotFoundError(f"no source file found in {project} (tried {candidates})")


def run_stage(stage_input: StageInput) -> StageOutput:
    src = stage_input.inputs.rust_project
    dst = stage_input.outputs.rust_project
    assert src is not None and dst is not None

    source_file = pick_source_file(src, stage_input.config)
    limit = int(stage_input.config.get("max_source_chars", 20000))
    source_text = source_file.read_text(encoding="utf-8")[:limit]

    # Prompt: stage-local library, versioned, content-hashed.
    library = PromptLibrary(Path(__file__).parent / "prompts")
    template = library.get("translation_notes")
    rendered = template.render(file_name=source_file.name, source=source_text)

    # Client + tracker straight from the envelope. The framework merged
    # global [llm] with this stage's [stages.example_llm.llm] override.
    settings = stage_input.framework.llm
    tracker = None
    if stage_input.framework.usage_log is not None:
        tracker = UsageTracker(
            stage_input.framework.usage_log,
            run_id=stage_input.run_id,
            stage=stage_input.stage_id,
            item=stage_input.item,
        )
    client = LlmClient(settings, tracker=tracker)
    response = client.complete(
        Request(
            messages=(Message(role="user", content=rendered.text),),
            temperature=0.0,
            metadata=RequestMetadata(
                run_id=stage_input.run_id,
                stage=stage_input.stage_id,
                item=stage_input.item,
                prompt_id=rendered.id,
                prompt_version=rendered.version,
                prompt_hash=rendered.content_hash,
            ),
        )
    )

    shutil.copytree(src, dst)
    (dst / "TRANSLATION_NOTES.md").write_text(
        f"<!-- generated by {STAGE_ID} via {response.provider}/{response.model} -->\n\n"
        + response.text.strip()
        + "\n",
        encoding="utf-8",
    )

    return StageOutput(
        status="success",
        stage_id=STAGE_ID,
        stage_version=STAGE_VERSION,
        outputs=OutputDestinations(rust_project=dst),
        config_used=dict(stage_input.config),
        models=(ModelInfo(provider=response.provider, model=response.model),),
        usage=UsageSummary(
            calls=1,
            input_tokens=response.usage.input_tokens,
            cached_input_tokens=response.usage.cached_input_tokens,
            output_tokens=response.usage.output_tokens,
            reasoning_tokens=response.usage.reasoning_tokens,
        ),
        prompts=(PromptUse(id=rendered.id, version=rendered.version),),
        metrics={
            "source_file": source_file.name,
            "notes_chars": len(response.text),
            "latency_s": round(response.latency_s, 2),
        },
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()

    stage_input = StageInput.read(args.input)
    try:
        output = run_stage(stage_input)
    except LlmError as exc:
        output = StageOutput(
            status="failure",
            stage_id=STAGE_ID,
            stage_version=STAGE_VERSION,
            error=(
                f"LLM call failed: {exc} — is the provider API key set "
                f"(e.g. ANTHROPIC_API_KEY)? Configure provider/model under "
                f"[llm] in the pipeline config."
            ),
        )
    except Exception as exc:  # never die without an envelope
        output = StageOutput(
            status="failure",
            stage_id=STAGE_ID,
            stage_version=STAGE_VERSION,
            error=f"{type(exc).__name__}: {exc}",
        )
    output.write(args.output)
    return 0 if output.status != "failure" else 1


if __name__ == "__main__":
    sys.exit(main())
